
debian/tmp/usr/share/pyshared/shinken/webui                                       /usr/share/pyshared/shinken/
debian/tmp/usr/share/pyshared/shinken/modules/active_directory_ui.py              /usr/share/pyshared/shinken/
debian/tmp/usr/share/pyshared/shinken/modules/passwd_ui.py                        /usr/share/pyshared/shinken/

debian/tmp/usr/share/pyshared/shinken/modules/webui_broker                        /usr/share/pyshared/shinken/modules/

debian/config-files/etc/shinken/htpasswd.users                                                 /etc/shinken/
