debian/tmp/usr/share/pyshared/shinken/modules/dummy_scheduler.py                  /usr/share/pyshared/shinken/modules/
debian/tmp/usr/share/pyshared/shinken/modules/memcache_retention_scheduler.py     /usr/share/pyshared/shinken/modules/
debian/tmp/usr/share/pyshared/shinken/modules/nagios_retention_file_scheduler.py  /usr/share/pyshared/shinken/modules/
debian/tmp/usr/share/pyshared/shinken/modules/pickle_retention_file_scheduler.py  /usr/share/pyshared/shinken/modules/
debian/tmp/usr/share/pyshared/shinken/modules/redis_retention_scheduler.py        /usr/share/pyshared/shinken/modules/

debian/tmp/usr/share/pyshared/shinken/daemons/schedulerdaemon.py                  /usr/share/pyshared/shinken/daemons/

debian/tmp/usr/bin/shinken-scheduler                                                           /usr/bin

debian/tmp/etc/init.d/shinken-scheduler                                                        /etc/init.d/
