debian/tmp/usr/share/pyshared/shinken/*.py                                        /usr/share/pyshared/shinken/

debian/tmp/usr/share/pyshared/shinken/objects/*.py                                /usr/share/pyshared/shinken/objects/

debian/tmp/usr/share/pyshared/shinken/daemons/__init__.py                         /usr/share/pyshared/shinken/daemons/

debian/tmp/usr/share/pyshared/shinken/modules/__init__.py                         /usr/share/pyshared/shinken/modules/
debian/tmp/usr/share/pyshared/shinken/modules/named_pipe.py                       /usr/share/pyshared/shinken/modules/
debian/tmp/usr/share/pyshared/shinken/modules/nsca.py                             /usr/share/pyshared/shinken/modules/
debian/tmp/usr/share/pyshared/shinken/modules/pickle_retention_file_generic.py    /usr/share/pyshared/shinken/modules/
debian/tmp/usr/share/pyshared/shinken/misc                                        /usr/share/pyshared/shinken



debian/tmp/usr/share/pyshared/Shinken-0.6.egg-info                                /usr/share/pyshared/

debian/tmp/usr/lib/shinken                                                                     /usr/lib/

debian/tmp/etc/default                                                                         /etc/

debian/config-files/etc/shinken/*.ini                                                          /etc/shinken/
debian/config-files/etc/shinken/objects/*                                                      /etc/shinken/objects/
# [a-v]*.cfg include everything except webui.cfg
debian/config-files/etc/shinken/[a-v]*.cfg                                                     /etc/shinken/

debian/tmp/etc/init.d/shinken                                                                  /etc/init.d

libexec/*.sh                                                                                   /usr/lib/shinken/plugins
libexec/*.py                                                                                   /usr/lib/shinken/plugins
