debian/tmp/usr/share/pyshared/shinken/daemons/pollerdaemon.py                     /usr/share/pyshared/shinken/daemons/

debian/tmp/usr/share/pyshared/shinken/modules/dummy_poller.py                     /usr/share/pyshared/shinken/modules/
debian/tmp/usr/share/pyshared/shinken/modules/nrpe_poller.py                      /usr/share/pyshared/shinken/modules/

debian/tmp/usr/bin/shinken-poller                                                              /usr/bin

debian/tmp/etc/init.d/shinken-poller                                                           /etc/init.d/
